# Site settings
title: Matti Salokangas, full stack software developer
email: matti.salokangas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I make things with code
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sturdynut.com" # the base hostname & protocol for your site
twitter_username: matticodes
github_username:  sturdynut

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-minifier
paginate_path: /blog/page:num
paginate: 5
permalink: pretty
sass:
  style: :compressed

# Assets Pipeline
assets:
  sources:
    - _assets
    - _assets/images
    - _assets/javascripts
    - _assets/css
    - _assets/fonts
    - _assets/downloads
