# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sturdy Nut
email: matti.salokangas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Matti Salokangas.  I am a unicorn developer.  When I write code I like to pretend I'm playing the piano.  Thanks for stopping by.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sturdynut.com" # the base hostname & protocol for your site
twitter_username: sturdynut
github_username:  sturdynut

# Build settings
markdown: kramdown
