# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sturdy Nut
email: matti.salokangas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Matti Salokangas and I am a software developer focused on intuitive user experiences, great design and test-driven code.  I don't mind shaking things up and I actually intend to do so.  Enjoy and thanks for stopping by.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sturdynut.com" # the base hostname & protocol for your site
twitter_username: sturdynut
github_username:  sturdynut

# Build settings
markdown: kramdown
