# Site settings
title: Matti Salokangas, front-end developer in Oregon, USA
email: matti.salokangas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full stack software developer that excels in UI/UX, communication and leadership with 12+ years of professional experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sturdynut.com" # the base hostname & protocol for your site
twitter_username: sturdynut
github_username:  sturdynut

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-minifier
paginate_path: /blog/page:num
paginate: 5
permalink: pretty
sass:
  style: :compressed

# Assets Pipeline
assets:
  sources:
    - _assets
    - _assets/images
    - _assets/javascripts
    - _assets/css
    - _assets/fonts
    - _assets/downloads