# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sturdy Nut
email: matti.salokangas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My focus is on providing value to my clients through intuitive design and
  test-driven code.  This site is inspired by a decade of developing software and a backlog
  of thoughts on how things can be done better.  I hope to shake up things and shine some
  light on conventions that don't make sense or simply need to go away.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sturdynut.com" # the base hostname & protocol for your site
twitter_username: sturdynut
github_username:  sturdynut

# Build settings
markdown: kramdown
